//#include <libgoback.h>
#include <iostream>
#include <DataSource.h>
#include <WorkMode.h>

#include <curses.h>

void init_ncurses() {
	initscr();
	if (has_colors() == FALSE) {
		endwin();
		printf("Your terminal does not support color\n");
		exit(1);
	}
	keypad(stdscr, TRUE);   /* enable keyboard mapping */
	//(void) nonl();      /* tell curses not to do NL->CR/NL on output */
	(void) cbreak();        /* take input chars one at a time, no wait for \n */
	(void) noecho();        /* don't echo input */
	//nodelay(stdscr, TRUE);
	//idlok(stdscr, TRUE);    /* allow use of insert/delete line */
	start_color();
	if (use_default_colors() == OK)
		init_pair(1, COLOR_RED, -1);

	attron(COLOR_PAIR(1));
}

void close_ncurses(){
	attroff(COLOR_PAIR(1));
	endwin();
}

void print_line(ViewLine line) {
	// Print the blocks
	ViewLine::iterator j = line.begin();
	while (j != line.end()) {
		printw("%s", j->_str.c_str());
		j++;
	}
}

void print_view(WorkMode *wm, int numlines, int startline){
	// Print all the lines generated by the WorkMode
	for (int i = 0; i < numlines && i < LINES; i++) {
		ViewLine line = wm->getLine(i + startline);
		move(i, 0);
		print_line(line);
	}
	refresh();
}

int main(int argc, char *argv[]) {
	int key;
	int startline = 0;

	if (argc != 2){
		std::cout << "Usage: " << argv[0] << " file" << std::endl;
		exit(-1);
	}

	DataSource *ds = DataSource::create("file");
	if (!ds->open(argv[1])) {
		perror("open");
		delete ds;
		return 1;
	}

	WorkMode *wm = WorkMode::create("hex", ds);
	int numlines = wm->getNumberLines();

	init_ncurses();

	print_view(wm, numlines, 0);
	for (;;) {
		key = getch();
		switch (key) {
		case KEY_DOWN:
			(startline == numlines) ? numlines : startline++;
			break;
		case KEY_UP:
			(startline == 0) ? 0 : startline--;
			break;
		case KEY_NPAGE:
			(startline + LINES > numlines) ? 0 : startline += LINES;
			break;
		case KEY_PPAGE:
			(startline - LINES < 0) ? 0 : startline -= LINES;
			break;
		case 'q':
			goto exit;
			break;
		}
		print_view(wm, numlines, startline);
	}

	exit:
	close_ncurses();
	ds->close();
	return 0;
}
